language: python
sudo: false
python:
  - "2.7"
services:
  - couchdb
env:
  - TZ=Europe/Kiev
cache:
  directories:
    - eggs
before_install:
  - pip install setuptools==7.0
  - python2 bootstrap.py
install:
  - bin/buildout -N
script:
  - bin/nosetests --process-restartworker
after_success:
  - bin/coveralls
notifications:
  webhooks:
    urls:
    on_success: true
    on_failure: true
    on_start: false
